### ISSUE TITLE
brittle link to expanding states

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#189]
This caught us in #81 

To expand the NHD states in the pull, we currently use

```yaml
  nhd_HR_download_plan:
    command: create_nhd_HR_download_plan(I(c("North_Dakota","South_Dakota","Iowa","Michigan","Indiana","Illinois","Wisconsin",
      "Minnesota", "New_York", "Pennsylvania", "Missouri")),
      min_size = I(40000))
```
(but see #188 ) to specify states. But in other targets:

```yaml
  1_crosswalk_fetch/out/LAGOS_lakes_sf.rds.ind:
    command: LAGOS_zip_to_sf(
      out_ind = target_name,
      layer = I("LAGOS_NE_All_Lakes_4ha"),
      zip_ind = '1_crosswalk_fetch/in/LAGOS_NE_All_Lakes_4ha.zip.ind',
      states = I(c("IA", "IN", "SD", "ND", "MI", "MN", "WI", "IL")))

  1_crosswalk_fetch/out/MGLP_lakes_sf.rds.ind:
    command: MGLP_zip_to_sf(
      out_ind = target_name,
      gdb_file = I("MGLP_model_data&results.gdb"),
      zip_ind = '1_crosswalk_fetch/in/MGLP_lakes.zip.ind',
      states = I(c("IA", "IN", "SD", "ND", "MI", "MN", "WI", "IL")))
```

This is too many places to specify states, and it is brittle. We should link these things appropriately.
